DEFAULT:
  music_dir: G:\.shortcut-targets-by-id\1ShQOk756cGk_SI7RBmZbk5yNIua8oii4\Files\Music
  radios:
    Radio 1:
      type: SRSRadio
      mode: 1
      frequency: '32.0'
      modulation: FM
      coalition: 2
      volume: '0.5'
      display_name: Blue Side Blues
    Radio 2:
      type: SRSRadio
      mode: 1
      frequency: '262.0'
      modulation: AM
      coalition: 1
      volume: '0.5'
      display_name: Red Side Rock
